export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const FECHING_DATA = "FECHING_DATA";
export const FECHING_DATA_SUCCESS = "FECHING_DATA_SUCCESS";
export const FECHING_DATA_FIALURE = "FECHING_DATA_FIALURE";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const UPDATE_USER = "UPDATE_USER";
export const GET_MOTORCICLES = "GET_MOTORCICLES";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const INVESTMENT_SUCCESS = "INVESTMENT_SUCCESS";
export const BALANCE_TOTAL_SUCCESS = "BALANCE_TOTAL_SUCCESS";
export const FECHING_DATA_PROFILE_SUCCESS = "FECHING_DATA_PROFILE_SUCCESS";
export const FECHING_DATA_APP_SUCCESS = "FECHING_DATA_APP_SUCCESS";
export const FECHING_MOTORCICLES_SUCCESS = "FECHING_MOTORCICLES_SUCCESS";
export const SET_MESSAGE_REGISTER = "SET_MESSAGE_REGISTER";
export const IS_RAPPI_TENDERO_SUCCESS = "IS_RAPPI_TENDERO_SUCCESS";
export const PROFILE_RAPPI_TENDERO_SUCCESS = "PROFILE_RAPPI_TENDERO_SUCCESS";
export const GET_DATA_CREDIT_SUCCESS = "GET_DATA_CREDIT_SUCCESS";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAGO_TOTAL_SUCCESS = "PAGO_TOTAL_SUCCESS";

// PAYMENT_SUCCESS;

// PAGO_TOTAL_SUCCESS;
