export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const FECHING_DATA = "FECHING_DATA";
export const FECHING_DATA_SUCCESS = "FECHING_DATA_SUCCESS";
export const FECHING_DATA_FIALURE = "FECHING_DATA_FIALURE";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const UPDATE_USER = "UPDATE_USER";
export const GET_MOTORCICLES = "GET_MOTORCICLES";
